version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: always
    env_file: '/home/user/env.d/watchtower.env'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock